#ifndef McuMagicTag_FEATURE_H
#define McuMagicTag_FEATURE_H

#define MACRO_ENABLE 1
#define MACRO_DISABLE 0

#define CHIP_3066HAPIMM MACRO_ENABLE

/* This firmware image runs on CPU0. */
#define APP_CORE_ID 0U

/* Enable the NOS task scheduler. */
#define NOS_TASK_SUPPORT

#define BASE_DEFINE_USE_ASSERT MACRO_ENABLE
#ifndef FLASH_CRC_CONFIG
#define FLASH_CRC_CONFIG
#endif
#define BASE_MATH_SINCOS_MIDDLE_TABLE MACRO_ENABLE

#define MCS_PARAM_CHECK MACRO_ENABLE
#define APT_PARAM_CHECK MACRO_ENABLE
#define ADC_PARAM_CHECK MACRO_ENABLE
#define CAPM_PARAM_CHECK MACRO_ENABLE
#define CRG_PARAM_CHECK MACRO_ENABLE
#define I2C_PARAM_CHECK MACRO_ENABLE
#define UART_PARAM_CHECK MACRO_ENABLE
#define SPI_PARAM_CHECK MACRO_ENABLE
#define TIMER_PARAM_CHECK MACRO_ENABLE
#define IWDG_PARAM_CHECK MACRO_ENABLE
#define WWDG_PARAM_CHECK MACRO_ENABLE
#define GPIO_PARAM_CHECK MACRO_ENABLE
#define GPT_PARAM_CHECK MACRO_ENABLE
#define DMA_PARAM_CHECK MACRO_ENABLE
#define CRC_PARAM_CHECK MACRO_ENABLE
#define CFD_PARAM_CHECK MACRO_ENABLE
#define CMM_PARAM_CHECK MACRO_ENABLE
#define CAN_PARAM_CHECK MACRO_ENABLE
#define FLASH_PARAM_CHECK MACRO_ENABLE
#define PMC_PARAM_CHECK MACRO_ENABLE
#define ACMP_PARAM_CHECK MACRO_ENABLE
#define DAC_PARAM_CHECK MACRO_ENABLE
#define PGA_PARAM_CHECK MACRO_ENABLE
#define IOCMG_PARAM_CHECK MACRO_ENABLE
#define QDM_PARAM_CHECK MACRO_ENABLE
#define FMC_PARAM_CHECK MACRO_ENABLE
#define IPCM_PARAM_CHECK MACRO_ENABLE
#define MAU_PARAM_CHECK MACRO_ENABLE
#define MBX_PARAM_CHECK MACRO_ENABLE
#define SRM_PARAM_CHECK MACRO_ENABLE
#define CPM_PARAM_CHECK MACRO_ENABLE

#define BOARD_DIM_NUM 1
#define BOARD_KEY_NUM 10
#define BOARD_KEY_PRESS_ON GPIO_HIGH_LEVEL
#define BOARD_KEY_PRESS_OFF GPIO_LOW_LEVEL
#define BOARD_LED_SEG_NUM 4
#define BOARD_LED_SEGMENT_ON GPIO_HIGH_LEVEL
#define BOARD_LED_SEGMENT_OFF GPIO_LOW_LEVEL
#define BOARD_MKEY_SCHEME_NUMBER BOARD_MKEY_SCHEME_NUMBER_ONE
#define BOARD_MKEY_OUT_NUM 4
#define BOARD_MKEY_IN_NUM 4
#define BOARD_MKEY_OUT_PIN_VALID GPIO_LOW_LEVEL
#define BOARD_MKEY_OUT_PIN_INVALID GPIO_HIGH_LEVEL
#define BOARD_MKEY_IN_PIN_VALID GPIO_LOW_LEVEL
#define BOARD_MKEY_IN_PIN_INVALID GPIO_HIGH_LEVEL
#define BOARD_PULSES_NUM 2
#define BASE_DEFINE_SLIPAVERAGE_NUM 2
#define LISTNODE_MAX 20
#define BASE_DEFINE_DMA_QUICKSTART
#define XTRAIL_FREQ 30000000U
#define DBG_USE_NO_PRINTF 0U
#define DBG_USE_UART_PRINTF 1U
#define DBG_PRINTF_USE DBG_USE_UART_PRINTF
#if (DBG_PRINTF_USE == DBG_USE_UART_PRINTF)
#define DBG_PRINTF_UART_PORT UART1
#endif

#endif
